def mainDir="Chapter02/2-jenkins-docker"
def ecrLoginHelper="docker-credential-ecr-login"
def region="<AWS Region>"
def ecrUrl="<AWS ECR URL>"
def repository="<JKTEST>"
def deployHost="<129.154.192.119>"

pipeline {
    agent any

    stages {
        stage('Pull Codes from Github'){
            steps{
                checkout scm
            }
        }
        stage('Build Codes by Gradle') {
            steps {
                sh """
                cd ${mainDir}
                ./gradlew clean build
                """
            }
        }
        stage('Build Docker Image by Jib & Push to AWS ECR Repository') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'azure_acr_rredential', passwordVariable: 'password', usernameVariable: 'username')]) {
                            sh """
                                cd ${mainDir}
                                az acr login -n jktest -u $(username) -p $(password) 
                                ./gradlew jib -Djib.to.image=jktest.azurecr.io -Djib.console='plain'
                            """
                        }
            }
        }
        stage('Deploy to AWS EC2 VM'){
            steps{
                sshagent(credentials : ["deploy-key"]) {
                    sh "ssh -o StrictHostKeyChecking=no ubuntu@${deployHost} \
                     'aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${ecrUrl}/${repository}; \
                      docker run -d -p 80:8080 -t ${ecrUrl}/${repository}:${currentBuild.number};'"
                }
            }
        }
    }
}
